export enum DNS_ERROR_TYPES {
  DOMAIN_NOT_FOUND = 'DOMAIN_NOT_FOUND',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  UNKNOWN = 'UNKNOWN',
}

export enum DNS_ERROR_CODES {
  CONNECTION_REFUSED = 'ECONNREFUSED',
  TIMEOUT = 'ETIMEDOUT',
  CONNECTION_RESET = 'ECONNRESET',
  NOT_FOUND = 'ENOTFOUND',
}

export const DNS_TIMEOUT_MS = 5000;
